### ISSUE TITLE
Chrome gets stuck in a loop when an image can not be found

### ISSUE THREAD

**Issue by piersroberts** [aFarkas/respimage#33]
When an image fails to load the browser it will continue to try and fetch the image over and over again.

This can become problematic if you're hitting a resource that is not protected by a CDN, like an html page. You could potentially end up DDoS attacking yourself.

Observed in Chrome 38.0.2125.104

![screen shot 2014-12-12 at 16 08 44](https://cloud.githubusercontent.com/assets/362272/5414749/6df9c1d2-8219-11e4-83c9-ef924baa5137.png)

```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>RESPIMAGE TEST</title>
</head>
<body>
<img
    srcset="http://placehold.it/466x200 466w,
        http://placehold.it/700x300 700w,
        http://example.com/1050x450 1050w,
        http://placehold.it/1400x600 1400w"
    sizes="(max-width: 1000px) calc(100vw - 20px), 1000px"
    src="http://placehold.it/250x107"
    alt="flexible image" />

<script src="respimage.js" async=""></script>
</body>
</html>
```

**Comment by danbondfuture** [comment]
Hi, I still have the same issue in chrome latest - will provide test case...
