### ISSUE TITLE
How to opt out of the on dom ready triggering of respimage

### ISSUE THREAD

**Issue by salzhrani** [aFarkas/respimage#35]
It seems to me that respimage is triggered on [dom ready](https://github.com/aFarkas/respimage/blob/gh-pages/respimage.dev.js#L1080) event. is there a way to opt out of this behaviour ?

**Comment by aFarkas** [comment]
respimage is already run also ealier. It is crucial to polyfill images as soon as possible. You can monkeypatch the ``respimage._.fillImgs`` to intercept polyfill calls, but in 90% of all use cases you should find another way.

What do you want to achieve exactly?

**Comment by salzhrani** [comment]
I set the srcset property lazily. So I want the polyfill to process the image after setting the property. I tried to use the reevaluate option but it didn't help

**Comment by aFarkas** [comment]
Ok, this is not the way to go.

In case you don't need to support IE8, I suggest that you use the [mutation plugin](https://github.com/aFarkas/respimage/tree/gh-pages/plugins/mutation).

With this plugin scripting respimg makes fun. For example you don't need ``setAttribute``/``getAttribute`` you can use the ``srcset`` property for example.

```js
document.querySelector('img').srcset = 'foo.jpg 200w';
```

In case you need to support IE8, have a look [how I'm handling it](https://github.com/aFarkas/respimage/blob/gh-pages/plugins/mutation/ri.mutation.js#L220-227).

**Comment by salzhrani** [comment]
Having to load an entire plugin to trigger a straightforward behaviour is not the answer I was looking for. All I need is either not to process images on load, or process them but allow me to force a reprocess prevented by the initial processing of images.

**Comment by aFarkas** [comment]
Using this plugin is actually a nice and straight forward solution. The filesize of this plugin only adds 2kb gzipped, so it's quite small.

In case you don't want to load it. You need to use the reparse option for triggering reparsing, but in case you have also changed the ``srcset`` attribute of the image, it's a little bit more complicated and you need to remove the cached ``srcset``.

```js
var img = document.querySelctor('img');
img.setAttribute('sizes', '33vw');
respimage({reparse: true, elements: [img]});
```

```js
var img = document.querySelctor('img');
img.setAttribute('srcset', 'image.jpg 2x');
if(img[respimage._.ns]){
    img[respimage._.ns].srcset = undefined;
}
respimage({reparse: true, elements: [img]});
```


I already give you 3 solutions: 
1. Use ``respimage._.fillImgs`` to intercept polyfill calls
2. Use the mutation plugin, this is exactly for what it was developed
3. Extract the same code used in this plugin or in [lazysizes](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L64-L71) to trigger a reparse or see the extraction above.

In case you want help I would appreciate it, if you would be a little bit more gentle.

**Comment by salzhrani** [comment]
Thank you for taking the time to help, I have nothing but respect and admiration for you and I apologize if my reply conveyed otherwise.

**Comment by aFarkas** [comment]
While I still think, you should give the mutation plugin a try. I made some improvements to the respimage API without the use of any plugin.

It is currently only in master and is [documented](https://github.com/aFarkas/respimage/tree/master#respimage-function). Feel free to test and maybe report some problems or in case you have a bugfix or an improvement for the documentation make a PR. Thank you.

**Comment by salzhrani** [comment]
I tried it and it works great for my use case ... will update if I run into any other issues. Thank you.

**Comment by aFarkas** [comment]
I tagged this version as an RC (https://github.com/aFarkas/respimage/releases/tag/1.3.0-RC1). All tests are run and green in all supported browsers/devices, so you should be good to go. Will release a new version in the next 1-2 days.

**Comment by salzhrani** [comment]
I just found that `reparse` works fine as long as you have a `src` property set, if it is not set even though `srcset` is set the image is not reevaluated. [this line](https://github.com/aFarkas/respimage/blob/gh-pages/respimage.dev.js#L961) might be the cause

**Comment by aFarkas** [comment]
Can you make a simple testcase what you mean here? Don't really understand. It works for me: here is my testcase:
http://jsfiddle.net/trixta/zemf3ytu/
As you see, the image has a ``src`` and I'm changing the srcset succesfully.

**Comment by aFarkas** [comment]
here is the same example without an initial src:
http://jsfiddle.net/trixta/zemf3ytu/4/

**Comment by salzhrani** [comment]
You are correct. `srcset` is not set properly and that is why I am getting this issue.

Thank you again.
