### ISSUE TITLE
Difference between respimage and picturefill?

### ISSUE THREAD

**Issue by pikeas** [aFarkas/respimage#38]
Based on some searching, it looks like respimage began as a fork of picturefill, but there's no reference to picturefill in your README currently? I'd love to see a short section describing the pros and cons of each project!

**Comment by aFarkas** [comment]
respimage is a picturefill fork based on version 2.2. In respimage all known bugs of picturefill are fixed, then some performance improvements for runtime as also network were added. Additionally there are some plugins available.

To simplify this: With respimage you basically get picturefill but with less bugs and a better performance.
