### ISSUE TITLE
Question: i have an image that changes CSS width and i'd like respimage to load the larger version, can i trigger this?

### ISSUE THREAD

**Issue by mkstix6** [aFarkas/respimage#39]
I'm just stuck on a little thing.

I have an image in a gallery.
When i click the image i'm changing a class that increases the image's container div css width from 20% width to 100% width. The image has 100% width so it increases in size.
When this happens i'd like to have the higher resolution image load in.

I can trigger the reload by changing the window size by 1px so i *think* it should be doable but i can't work out the syntax to trigger it.

Any help would be grand,
Thanks for respimage.

**Comment by aFarkas** [comment]
Yes you can. What you need to change basically depends on your markup. If you use ``srcset`` you need to change the ``sizes`` attribute and in case you use ``picuture`` you need to change the ``sizes`` attribute (if you are using width descriptors) and maybe also your ``media`` attributes.

You can see this featured here:
http://jsfiddle.net/trixta/gs3p14pr/embedded/result/

In case you are not using the mutation extension, you need to [trigger a reparse](https://github.com/aFarkas/respimage#respimage-function).

```js
var $imgs = $('img').attr('sizes', '300px');

respimage({elements: $imgs, reparse: true});
```

Please close this issue, if it helped.

**Comment by aFarkas** [comment]
@mkstix6 

Did this help? Also note: that starting with 1.4.0 the ``reparse`` option was renamed to ``reevaluate``.

**Comment by mkstix6** [comment]
Hi Alexander,
I'm currently working on a different project so i'd need to try this a little later. Sorry.
I'm happy to record this page and close the issue if you'd prefer?

I will keep in mind the reevaluate, i might have missed that.

Thanks for your help.

**Comment by mkstix6** [comment]
Sorry for the long LONG time to reply. I've got this working now with your help. Thanks a bunch.
Thanks for respimage.
