### ISSUE TITLE
Question: Is respimage affected by recent picturefill native picture-detection issue?

### ISSUE THREAD

**Issue by przemyslaw-piatek** [aFarkas/respimage#43]
As respimage is an improved fork of picturefill, does the issue stated in the following article affect it?
https://css-tricks.com/please-update-picturefill/

If so, is there any schedule for fixing it?

**Comment by aFarkas** [comment]
No, respimage was never affected by this issue. Here is the [original commit](https://github.com/scottjehl/picturefill/commit/1b41ba0556a92215af4f4464f8a675ada1cae162), which was the base for respimage.
