### ISSUE TITLE
Responsive image with srcset not working in IE8

### ISSUE THREAD

**Issue by Twansparant** [aFarkas/respimage#46]
Hi there,

I'm using a very simple markup with the img **srcset** tag and the **density x descriptor** like in your example: http://codepen.io/aFarkas/pen/KwKdpY
In IE8 the example is not working, no image is displayed?

```
<div class="image">
      <a class="zoom" itemprop="image" title="Monum Urn S'tone I Grijs" href="https://www.monum.nl/wp-content/uploads/2015/06/Fo_St_Bz_14-1024x1024.jpg" data-rel="prettyPhoto[page-gallery]">
          <img src="some-image-310x310.jpg" srcset="some-image-310x310.jpg 1x, some-image-310x310@2x.jpg 2x" alt="My alt" />
      </a>
</div>
```

I'm using your latest version v1.4.1.
Any idea? Thanks!

**Comment by aFarkas** [comment]
Sorry, can't replicate this issue. Doesn't ring a bell either. Can you give me a testcase or access to your site to test against.

**Comment by Twansparant** [comment]
It's happening on this page (both on test server as live): http://monum.dd-webtest.com/monum/
In the left column there should be 3 images beneath each other. They are being displayed for a split second then disappear.
Thanks!
